spring:
  application:
    name: store_rest_api_school_project

  datasource:
    url: jdbc:mariadb://localhost:3306/store
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
